runtime: python39
entrypoint: gunicorn -b :8080 app:app

env_variables:
  GOOGLE_API_KEY: 'AIzaSyDokXpf-6hNH7Rzjynbnj4rphFXfqNA9u4'
  FLASK_DEBUG: 1

instance_class: F2
automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.7
  target_throughput_utilization: 0.7

readiness_check:
  path: "/"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 1800

error_handlers:
- file: default_error.html

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto
